export const SET_CURRENT_SEARCH_TERM = 'SET_CURRENT_SEARCH_TERM'
export const RESET_CURRENT_SEARCH_TERM = 'RESET_CURRENT_SEARCH_TERM'

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
export const RESET_CURRENT_PAGE = 'RESET_CURRENT_PAGE'
